apiVersion: v1
kind: Secret
metadata:
  name: avp-test
  namespace: default
  annotations:
    avp.kubernetes.io/path: "{{ .Values.vaultSecretPath }}"
type: Opaque
stringData:
  user: <path:{{ .Values.vaultSecretPath }}#user>
  pass: <path:{{ .Values.vaultSecretPath }}#pass>
